server: 
  port: 8080

spring: 
    datasource: 
        url: jdbc:mysql://127.0.0.1:3306/tuzisong?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&&serverTimezone=UTC
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
mybatis: 
  typeAliasesPackage: com.example.model
  mapperLocations: classpath:mapper/*.xml