server:
  contextPath: /hello-world-b
  port: 8077
logging:
  file: build/hello-world-b.log
  level:
    com.gaodashang.demo: DEBUG
context:
  listener:
    classes:
      com.gaodashang.demo.ApplicationStartup
