spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
  thymeleaf:
    encoding: UTF-8
    cache: false

server:
  port: 8080
  uri-encoding: UTF-8
  max-threads: 100

mybatis:
  typeAliasesPackage: com.mybatisboot.entity
  mapperLocations: classpath:mapper/*Mapper.xml